eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
microservice:
  flight-service:
    get-scheduled-flight-by-id: http://FLIGHT-SERVICE/api/v1/
    

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer 
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: common.config.kafka
              
          
kafka:
  request:
    topic: order-get-balance
  reply:
    topic: order-reply-balance
  group:
    id: order-balance
  
