eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
microservice:
  flight-service:
    get-scheduled-flight-by-id: http://FLIGHT-SERVICE/api/v1/scheduled-flight/
    

                        
kafka:
  request:
    topic: order-get-balance
  reply:
    topic: order-reply-balance
  group:
    id: order-balance
